import React from 'react';
import { useNavigate } from 'react-router-dom';
import type { InsightItem } from '../../types/ai';

interface Props {
  insight: InsightItem;
  onClose: () => void;
  onNavigate?: () => void;
}

const severityConfig = {
  info:     { icon: 'ℹ', color: 'text-blue-500', bg: 'bg-blue-500/10' },
  warning:  { icon: '⚠', color: 'text-amber-500', bg: 'bg-amber-500/10' },
  critical: { icon: '✕', color: 'text-red-500', bg: 'bg-red-500/10' },
  positive: { icon: '✓', color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
};

const InsightFocusView: React.FC<Props> = ({ insight, onClose, onNavigate }) => {
  const navigate = useNavigate();
  const sc = severityConfig[insight.severity];

  const handleAction = () => {
    if (insight.action?.href) {
      if (onNavigate) onNavigate(); // Closes the main modal
      onClose(); // Closes this focus view
      navigate(insight.action.href);
    }
  };

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-950/40 backdrop-blur-md animate-in fade-in duration-300"
        onClick={onClose}
      />
      
      {/* Content */}
      <div className="relative w-full max-w-lg bg-white dark:bg-[#1a1625] rounded-[32px] shadow-2xl border border-slate-200 dark:border-white/10 overflow-hidden animate-in zoom-in-95 slide-in-from-bottom-4 duration-500">
        {/* Header */}
        <div className={`px-6 py-6 ${sc.bg} flex items-center justify-between`}>
          <div className="flex items-center gap-3">
            <span className={`w-8 h-8 rounded-full ${sc.bg} border border-current flex items-center justify-center font-bold`}>
              {sc.icon}
            </span>
            <h3 className="text-sm font-black uppercase tracking-widest text-slate-800 dark:text-white">
              Executive Deep-Dive
            </h3>
          </div>
          <button 
            onClick={onClose}
            className="w-8 h-8 rounded-full hover:bg-black/5 dark:hover:bg-white/5 flex items-center justify-center text-slate-400 transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="p-8 space-y-6">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-brand-primary mb-2">Insight Headline</p>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white leading-tight">
              {insight.headline}
            </h2>
          </div>

          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">Executive Summary</p>
            <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed font-medium">
              {insight.summary}
            </p>
          </div>

          {insight.detail && (
            <div className="bg-slate-50 dark:bg-white/5 rounded-2xl p-5 border border-slate-100 dark:border-white/5">
              <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-3">Technical Analysis</p>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed italic">
                {insight.detail}
              </p>
            </div>
          )}

          {insight.action && (
            <div className="pt-4">
              <button
                onClick={handleAction}
                className="w-full inline-flex items-center justify-center gap-2 px-6 py-4 bg-brand-primary text-white rounded-2xl text-sm font-bold shadow-lg shadow-brand-primary/20 hover:shadow-brand-primary/40 hover:-translate-y-0.5 transition-all"
              >
                {insight.action.label} 
                <span className="text-lg">→</span>
              </button>
            </div>
          )}
        </div>
        
        {/* Footer subtle brand */}
        <div className="px-8 py-4 bg-slate-50/50 dark:bg-white/2 border-t border-slate-100 dark:border-white/5 text-center">
          <p className="text-[9px] font-bold text-slate-400 uppercase tracking-[0.2em]">
            Generated by Royalgateway Intelligence Hub
          </p>
        </div>
      </div>
    </div>
  );
};

export default InsightFocusView;
